# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: docker-tui

before:
  hooks:
    - go mod tidy

builds:
  - id: docker-tui
    main: ./cmd/docker-tui
    binary: docker-tui
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/guilhermepantoja789/docker-tui/internal/version.Version={{.Version}}
      - -X github.com/guilhermepantoja789/docker-tui/internal/version.Commit={{.Commit}}
      - -X github.com/guilhermepantoja789/docker-tui/internal/version.Date={{.Date}}

archives:
  - id: default
    formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE
      - README.md

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: guilhermepantoja789
    name: docker-tui
